language: android
android:
  components:
    - android-28
    - build-tools-29.0.2
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
before_install:
        - chmod +x gradlew
        - touch local.properties
branches:
        only:
                - master
